# yaml - comfortable for read and fetch data in our Spring

spring:
  application:
    name: taskflow

  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    com.elmirsurkeev.taskmanager: DEBUG
    org.springframework.security: DEBUG